endpoint: https://127.0.0.1/api/v1
insecure: true
auth:
  basic:
    enabled: true
    user: admin
    password: VRCm9L80yO3FHTKeVthtxknfGq1b10WqInKoBFqozphGcrGi
  oauth2:
    enabled: false
    authUrl: https://github.com/login/oauth/authorize
    tokenUrl: https://github.com/login/oauth/access_token
    clientId: xxxxxxxxxxxxxx
    clientSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
    scopes:
      - profile
  x509:
    certPath: ~/.config/floodgate/floodgate.crt
    enabled: false
    keyPath: ~/.config/floodgate/floodgate.key
libraries:
  - sponnet
resources:
  - resources/applications
  - resources/pipelines
  - resources/pipelinetemplates